services:
  mongo:
    image: mongo
    container_name: messaging_mongo
    ports:
      - "27017:27017"

  redis:
    image: redis
    container_name: messaging_redis
    ports:
      - "6379:6379"

  neo4j:
    image: neo4j
    container_name: messaging_neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password123